// <auto-generated />
using System;
using DernSupport_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DernSupport_BackEnd.Migrations
{
    [DbContext(typeof(DernSupportDbContext))]
    [Migration("20240912010728_AddModelsAndDbContextAndRelashinShips")]
    partial class AddModelsAndDbContextAndRelashinShips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DernSupport_BackEnd.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.JobSparePart", b =>
                {
                    b.Property<int>("JobSparePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobSparePartId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("JobSparePartId");

                    b.ToTable("JobSparePartDb");

                    b.HasData(
                        new
                        {
                            JobSparePartId = 1,
                            Category = "GPU",
                            Description = "NVIDIA GeForce GTX 1650",
                            Name = "Graphics Card",
                            QuantityInStock = 6
                        },
                        new
                        {
                            JobSparePartId = 2,
                            Category = "Cooling",
                            Description = "Laptop Cooling Fan Assembly",
                            Name = "Cooling Fan",
                            QuantityInStock = 7
                        },
                        new
                        {
                            JobSparePartId = 3,
                            Category = "Storage",
                            Description = "DVD-RW Optical Drive",
                            Name = "Optical Drive",
                            QuantityInStock = 5
                        },
                        new
                        {
                            JobSparePartId = 4,
                            Category = "Input",
                            Description = "Laptop Touchpad Assembly",
                            Name = "Touchpad",
                            QuantityInStock = 9
                        },
                        new
                        {
                            JobSparePartId = 5,
                            Category = "Camera",
                            Description = "HD Webcam for Laptops",
                            Name = "Webcam",
                            QuantityInStock = 11
                        },
                        new
                        {
                            JobSparePartId = 6,
                            Category = "Power",
                            Description = "500W Power Supply Unit",
                            Name = "Power Supply",
                            QuantityInStock = 8
                        },
                        new
                        {
                            JobSparePartId = 7,
                            Category = "Enclosure",
                            Description = "Mid-Tower Computer Case",
                            Name = "Case",
                            QuantityInStock = 13
                        },
                        new
                        {
                            JobSparePartId = 8,
                            Category = "Accessory",
                            Description = "7-Port USB 3.0 Hub",
                            Name = "USB Hub",
                            QuantityInStock = 14
                        });
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.Jobs", b =>
                {
                    b.Property<int>("JobsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobsId"));

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduledDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobsId");

                    b.ToTable("JobsDb");

                    b.HasData(
                        new
                        {
                            JobsId = 1,
                            Cost = "300$",
                            Description = "Perform a backup of the company’s critical data.",
                            Priority = "High",
                            ScheduledDate = "",
                            Title = "Data Backup"
                        },
                        new
                        {
                            JobsId = 2,
                            Cost = "150$",
                            Description = "Set up email accounts for new employees.",
                            Priority = "High",
                            ScheduledDate = "",
                            Title = "Email Configuration"
                        },
                        new
                        {
                            JobsId = 3,
                            Cost = "400$",
                            Description = "Update server operating system and software.",
                            Priority = "Medium",
                            ScheduledDate = "",
                            Title = "Server Maintenance"
                        },
                        new
                        {
                            JobsId = 4,
                            Cost = "90$",
                            Description = "Replace damaged network cables in office.",
                            Priority = "Medium",
                            ScheduledDate = "",
                            Title = "Network Cable Replacement"
                        },
                        new
                        {
                            JobsId = 5,
                            Cost = "500$",
                            Description = "Test the backup system to ensure it is functioning correctly.",
                            Priority = "High",
                            ScheduledDate = "",
                            Title = "Backup System Testing"
                        },
                        new
                        {
                            JobsId = 6,
                            Cost = "30$",
                            Description = "Update all software to the latest versions.",
                            Priority = "Low",
                            ScheduledDate = "",
                            Title = "Software Update"
                        },
                        new
                        {
                            JobsId = 7,
                            Cost = "350$",
                            Description = "Take inventory of all IT equipment in the office.",
                            Priority = "Medium",
                            ScheduledDate = "",
                            Title = "IT Equipment Inventory"
                        });
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.KnowledgeBase", b =>
                {
                    b.Property<int>("KnowledgeBaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KnowledgeBaseId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KnowledgeBaseId");

                    b.ToTable("KnowledgeBases");

                    b.HasData(
                        new
                        {
                            KnowledgeBaseId = 1,
                            Category = "Hardware",
                            Description = "To install RAM, you must open your computer case, locate the RAM slots on the motherboard, and carefully insert the RAM sticks into the available slots. Ensure they are properly aligned before pressing them into place. After installation, close the case and restart your computer to check if the new RAM is recognized by the system.",
                            Title = "How do I install RAM in my computer?"
                        },
                        new
                        {
                            KnowledgeBaseId = 2,
                            Category = "Software",
                            Description = "Configuring Windows Firewall involves managing inbound and outbound rules for applications. This allows you to block unwanted traffic and only permit trusted software to communicate over the network. It's important to ensure that you regularly review and adjust firewall settings to protect your system from unauthorized access.",
                            Title = "How do I configure Windows Firewall for better security?"
                        },
                        new
                        {
                            KnowledgeBaseId = 3,
                            Category = "Hardware",
                            Description = "Replacing a hard drive requires removing the old drive from its bay, disconnecting the power and data cables, and installing a new one in its place. After installation, you’ll need to reinstall the operating system or restore your files from a backup. This process is crucial if you're upgrading to a larger drive or replacing a failed one.",
                            Title = "What is the process for replacing a hard drive?"
                        },
                        new
                        {
                            KnowledgeBaseId = 4,
                            Category = "Software",
                            Description = "To install Microsoft Office, download the installer from Office.com or use an installation disc. After the setup process, you’ll need to sign in with your Microsoft account to activate the product. You can then customize settings for applications like Word, Excel, and PowerPoint based on your preferences and needs.",
                            Title = "How do I install and set up Microsoft Office?"
                        },
                        new
                        {
                            KnowledgeBaseId = 5,
                            Category = "Hardware",
                            Description = "Troubleshooting printer issues involves checking for physical connection problems, verifying that the correct printer drivers are installed, and ensuring that there is enough ink or toner. Additional steps may include running diagnostic tests through the printer's software and resolving any network-related issues if the printer is connected wirelessly.",
                            Title = "How can I troubleshoot common printer issues?"
                        },
                        new
                        {
                            KnowledgeBaseId = 6,
                            Category = "Software",
                            Description = "If you've forgotten your Windows password, you can reset it using a password reset disk, another administrator account, or by using Microsoft's online account recovery tool. In some cases, you may need to boot into Safe Mode to reset the password manually. It's important to ensure you have recovery options set up beforehand to avoid being locked out.",
                            Title = "How do I reset a forgotten Windows password?"
                        },
                        new
                        {
                            KnowledgeBaseId = 7,
                            Category = "Software",
                            Description = "Updating drivers involves visiting the hardware manufacturer’s website, downloading the latest drivers, and installing them on your system. Alternatively, Windows Update can automatically download and install driver updates. Keeping drivers up to date ensures that your hardware components perform efficiently and remain compatible with the latest software.",
                            Title = "How do I update my computer's drivers?"
                        },
                        new
                        {
                            KnowledgeBaseId = 8,
                            Category = "Hardware",
                            Description = "To clean dust from your computer, turn off the system and disconnect it from power. Open the case and use compressed air to blow dust from the fans, heat sinks, and other components. Be careful not to touch internal parts with your hands. Regular cleaning prevents overheating and helps your computer run more efficiently.",
                            Title = "How do I clean dust from my computer?"
                        });
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Hours")
                        .HasColumnType("float");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Budget = "5000 JD",
                            Hours = 150.0,
                            ProjectName = "Project A"
                        },
                        new
                        {
                            ProjectId = 2,
                            Budget = "10000 JD",
                            Hours = 180.0,
                            ProjectName = "Project B"
                        },
                        new
                        {
                            ProjectId = 3,
                            Budget = "12000 JD",
                            Hours = 200.0,
                            ProjectName = "Project C"
                        });
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.Technician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechnicianId");

                    b.ToTable("technician");

                    b.HasData(
                        new
                        {
                            TechnicianId = 1,
                            Email = "hamadanjo@gmail.com",
                            FirstName = "Moayad",
                            LastName = "Hamdan",
                            Phone = "1245698785"
                        },
                        new
                        {
                            TechnicianId = 2,
                            Email = "aya@gmail.com",
                            FirstName = "Aya",
                            LastName = "Al-Wahidi",
                            Phone = "65489785425"
                        });
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.TechnicianProjects", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "TechnicianId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("TechnicianProjectsDBset");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            TechnicianId = 1
                        },
                        new
                        {
                            ProjectId = 2,
                            TechnicianId = 1
                        },
                        new
                        {
                            ProjectId = 1,
                            TechnicianId = 2
                        });
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.TechnicianTask", b =>
                {
                    b.Property<int>("TechnicianTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianTaskId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TechnicianTaskId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("userId");

                    b.ToTable("TechnicianTasksDb");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "user",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1990583211,
                            ClaimType = "permission",
                            ClaimValue = "Create",
                            RoleId = "admin"
                        },
                        new
                        {
                            Id = 1580734,
                            ClaimType = "permission",
                            ClaimValue = "Delete",
                            RoleId = "admin"
                        },
                        new
                        {
                            Id = -666972313,
                            ClaimType = "permission",
                            ClaimValue = "Delete",
                            RoleId = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.TechnicianProjects", b =>
                {
                    b.HasOne("DernSupport_BackEnd.Models.Project", "Project")
                        .WithMany("technicianProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DernSupport_BackEnd.Models.Technician", "Technician")
                        .WithMany("technicianProjects")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.TechnicianTask", b =>
                {
                    b.HasOne("DernSupport_BackEnd.Models.Technician", "technician")
                        .WithMany("technicianTasks")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DernSupport_BackEnd.Models.ApplicationUser", "applicationUser")
                        .WithMany("technicianTasks")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("applicationUser");

                    b.Navigation("technician");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DernSupport_BackEnd.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DernSupport_BackEnd.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DernSupport_BackEnd.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DernSupport_BackEnd.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.ApplicationUser", b =>
                {
                    b.Navigation("technicianTasks");
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.Project", b =>
                {
                    b.Navigation("technicianProjects");
                });

            modelBuilder.Entity("DernSupport_BackEnd.Models.Technician", b =>
                {
                    b.Navigation("technicianProjects");

                    b.Navigation("technicianTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
